### ISSUE TITLE
Zomby-ish processes sometimes when using `isolation: true`

### ISSUE THREAD

**Issue by jamieorc** [grosser/parallel#196]
I've started using `isolation: true` for data sets that are large and I know will consume large amounts of memory over time. 

I'm noticing that sometimes the `parallel.rb:203` commands I see under `top` show 0 processor usage. Processing just hangs indefinitely because these are doing nothing. If I kill each one from top (SIG 15), a new process starts up for each one, no problem. 

More context:

I'm running a nightly script that process Rails 4.x apps with large sets of data in Mongodb 3.0 using MongoMapper. 8 Processor Ubuntu 14.04 server with 16GB memory and 16GB virtual memory.

**Comment by grosser** [comment]
don't have any real pointers for you ... first time I hear about that ...
please update if you find something :)

On Wed, Mar 8, 2017 at 8:11 AM, Jamie Orchard-Hays <notifications@github.com

**Comment by jerith** [comment]
I've had problems using `isolation: true` in `puppet-catalog-test` builds on Travis, where `Parallel.map` sometimes hangs after the end of the last task but before returning. I haven't been able to reproduce this locally, so I can't tell if this is caused by "zomby-ish processes", but the hanging and the use of `isolation: true` seems to match @jamieorc's experience.

I think it might have something to do with Travis reporting 32 processors and `puppet-catalog-test` passing `:in_process => 32` to `Parallel.map`. Reducing the number of processes _seems_ to make it hang less frequently.

**Comment by jerith** [comment]
I've managed to do some more debugging on this, mostly by replacing various methods in `parallel.rb` with my own copies that emit vast quantities of debug logging.

The problem seems to be that sometimes an isolated worker is stopped (through `Worker.stop`, which closes the pipes and waits for the process to terminate) but doesn't actually receive the EOF that terminates the loop in `process_incoming_jobs`.

**Comment by jerith** [comment]
Aha! The cause of the problem seems to be a race condition in `replace_worker`. In order to close all the pipe endpoints to other workers that are inherited by the `fork`, `replace_worker` passes `started_workers: running` into the worker creation method. However, if multiple workers are replaced concurrently there's a race condition that can result in some new worker objects being in `workers` but not `running`.

As partial confirmation, adding a `sleep 0.5` (or some similar value) between https://github.com/grosser/parallel/blob/master/lib/parallel.rb#L410 and https://github.com/grosser/parallel/blob/master/lib/parallel.rb#L411 makes my test hang much more reliably.

I believe the solution is to either lock the relevant parts of `replace_worker` (which is just those two lines, I think) or to pass the whole `workers` array into the worker creation method and have that filter out `nil`s.

**Comment by grosser** [comment]
That sounds promising! Can you make a PR for that ... I can help with testing etc, but would like to see what exactly the solution you had in mind is.

**Comment by jerith** [comment]
I don't have a suitable dev environment set up for a PR, but here's the monkey-patch I'm using:
```ruby
module Parallel
  class << self
    old_replace_worker = instance_method(:replace_worker)

    define_method(:replace_worker) do |job_factory, workers, i, options, blk|
      options[:mutex].synchronize do
        old_replace_worker.bind(self).call(job_factory, workers, i, options, blk)
      end
    end
  end
end
```

I don't recall seeing any hangs since we added this to our `Rakefile`, when previously something like 80% of our builds had at least one job hang.

**Comment by jerith** [comment]
Ugh, I just had a build hang. I guess there's some other race that can cause this, but at least the frequency has gone down significantly.

**Comment by grosser** [comment]
1.11.2
