### ISSUE TITLE
Batch jobs up for efficiency

### ISSUE THREAD

**Issue by mikecmpbll** [grosser/parallel#213]
i was experiencing odd CPU usage patterns when using this library, i was struggling to get full utilisation. i noticed that the worker processes were often not at 100% CPU.

as i understand it, currently parallel workers will pick up a job off the queue when they finish their previous job. for jobs that are relatively short, it seems like possibly a large percentage of time spent processing a job is in marshalling the input the output, and other overhead associated with handing off to a worker. this seems to have a detrimental effect on efficiency when we have a large number of jobs and process workers.

to test this theory out i restructured my data into large batches, and had parallel process the batch instead.

```ruby
grouped_inputs = inputs.in_groups(opts[:processes], false)
results =
  Parallel.map_with_index(grouped_inputs, in_processes: opts[:processes]) do |inputs, i|
    inputs.map do |input|
      do_work(input)
    end
  end
results.flatten!(1)
```

if you have 1 million inputs and 64 process workers it would previously be marshalling 2 million times, and now just 128. prior to this change, it was taking > 1 hour (i stopped it ..), after the change it processes the inputs in 10 minutes ...

thought i'd put it here for info more than anything else, but if you think that the batching could be part of parallels options, i'm happy to make a PR.

**Comment by grosser** [comment]
Good fine, thanks for the info.
Kinda straight forward to use groups for this, so adding more code into parallel does not really help anyone.

The overhead might also be the inter-process communication instead of the marshaling. (Could verify that by using `each` instead of map, if it's slow too the it is not the marshaling)

Since making maximum size groups means some workers will finish early the optimum might be something like `inputs.in_groups(opts[:processes] * 10, false)`
