### ISSUE TITLE
rcov tests don't mark code in parallel blocks as covered

### ISSUE THREAD

**Issue by DGaffney** [grosser/parallel#282]
Hey all,

I have the smallest of issues that's low-level bothered me for a few months now. Searched in the history here and didn't find a reason - does anyone know why running test coverage in spec would result in non-coverage for lines of code executed within `parallel` blocks like so:

<img width="958" alt="Screen Shot 2020-09-17 at 11 01 52 AM" src="https://user-images.githubusercontent.com/14244/93489337-638b0880-f8d5-11ea-9d1f-2270d3d24fe1.png">

I am running the code surrounding this block, and I'm seeing the progress bars show up *within the test suites output*, so I can confirm that the lines are actually run - they just aren't noted as having run. Is there a way to convince rcov that it's happened?

**Comment by grosser** [comment]
it runs in a different process, so the coverage information is not stored in the correct process

https://github.com/grosser/forking_test_runner deals with that by capturing the extra coverage and merging it https://github.com/grosser/forking_test_runner/blob/master/lib/forking_test_runner/coverage_capture.rb
in this case that won't help much since you fork from within the running test and would have to return the additional coverage to the parent process and then merge which gets ugly.

A simpler workaround would be to do `in_processes: test? ? 0 : 5` so it executes without forking and everything is covered

**Comment by DGaffney** [comment]
Sounds reasonable. Thanks for the prompt reply and excellent gem @grosser
