### ISSUE TITLE
Sidekiq integration 

### ISSUE THREAD

**Issue by dortin42** [grosser/parallel#314]
Hi, I'm running some tests with ActiveJob, Rspec, Parallel and Sidekiq of course, putting jobs inside Parallel with any in_processes value than 0, makes jobs not to queue, but as I said, if I set in_processes = 0, all jobs are inqueued. Is this a Parallel's bug?

**Comment by grosser** [comment]
I'd assume they get queued in a separate thread that then gets killed ... need to configure the backend to be something persistent like redis for thisto work, or use `in_threads: X`

**Comment by dortin42** [comment]
@grosser but sidekiq uses redis by default... Do you mean an extra config? Maybe do you have some links about how to do that? I can't find anything

**Comment by grosser** [comment]
if it uses redis then that should work
reproduce by doing `fork { enqueue }` and if that does not work then open an issue with sidekiq
basically I don't think parallel is at faul since it just `fork`s so bug must be somewhere else
... might be something like that the enqueue does not directly write to redis but gets sent into some background thread and then that thread is killed, but no idea
